import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(body: ListView(children: [AOnBoarding()])),
    );
  }
}

class AOnBoarding extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 430,
          height: 932,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: const Color(0xFF00D09E),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(40),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 99,
                top: 443,
                child: Container(
                  width: 248,
                  height: 248,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFDFF7E2),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 72,
                top: 403.50,
                child: Container(
                  width: 287,
                  height: 287,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/287x287"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 181,
                top: 758,
                child: Text(
                  'Next',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: const Color(0xFF0E3E3E),
                    fontSize: 30,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w600,
                    height: 0.73,
                  ),
                ),
              ),
              Positioned(
                left: 194,
                top: 807,
                child: Container(
                  width: 13,
                  height: 13,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF00D09E),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 223,
                top: 807,
                child: Container(
                  width: 13,
                  height: 13,
                  decoration: ShapeDecoration(
                    shape: OvalBorder(
                      side: BorderSide(
                        width: 2,
                        color: const Color(0xFF0E3E3E),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 70,
                top: 123,
                child: SizedBox(
                  width: 289,
                  height: 122,
                  child: Text(
                    'Welcome to Expense Manager',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF0E3E3E),
                      fontSize: 30,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.30,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 430,
                  height: 32,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 37,
                        top: 9,
                        child: SizedBox(
                          width: 30,
                          height: 14,
                          child: Text(
                            '16:04',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 13,
                              fontFamily: 'League Spartan',
                              fontWeight: FontWeight.w500,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
