// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTBcVF2OyDy_jk4eQDMUy-NKVQPfCJanQ',
    appId: '1:29911992388:web:c663d8e0c57b58be58d411',
    messagingSenderId: '29911992388',
    projectId: 'myfinance-8d2bf',
    authDomain: 'myfinance-8d2bf.firebaseapp.com',
    storageBucket: 'myfinance-8d2bf.firebasestorage.app',
    measurementId: 'G-EF5ZHKXFYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSYgk0x5Gay52HviZPzcvv0zzgHrxqgnw',
    appId: '1:29911992388:android:5c77f3de48405c9d58d411',
    messagingSenderId: '29911992388',
    projectId: 'myfinance-8d2bf',
    storageBucket: 'myfinance-8d2bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdU4TUbhfV8tCTEc1pRxNlBFVKX0lXMU0',
    appId: '1:29911992388:ios:9de4dda6eae7986c58d411',
    messagingSenderId: '29911992388',
    projectId: 'myfinance-8d2bf',
    storageBucket: 'myfinance-8d2bf.firebasestorage.app',
    iosBundleId: 'com.example.lifehub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdU4TUbhfV8tCTEc1pRxNlBFVKX0lXMU0',
    appId: '1:29911992388:ios:9de4dda6eae7986c58d411',
    messagingSenderId: '29911992388',
    projectId: 'myfinance-8d2bf',
    storageBucket: 'myfinance-8d2bf.firebasestorage.app',
    iosBundleId: 'com.example.lifehub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTBcVF2OyDy_jk4eQDMUy-NKVQPfCJanQ',
    appId: '1:29911992388:web:53fd45a5db62c62358d411',
    messagingSenderId: '29911992388',
    projectId: 'myfinance-8d2bf',
    authDomain: 'myfinance-8d2bf.firebaseapp.com',
    storageBucket: 'myfinance-8d2bf.firebasestorage.app',
    measurementId: 'G-N87DKCC49R',
  );
}
