// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTBcVF2OyDy_jk4eQDMUy-NKVQPfCJanQ',
    appId: '1:29911992388:web:2781ad40d582670c58d411',
    messagingSenderId: '29911992388',
    projectId: 'myfinance-8d2bf',
    authDomain: 'myfinance-8d2bf.firebaseapp.com',
    storageBucket: 'myfinance-8d2bf.firebasestorage.app',
    measurementId: 'G-VB8X3E1H84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSYgk0x5Gay52HviZPzcvv0zzgHrxqgnw',
    appId: '1:29911992388:android:8771854ac01e898658d411',
    messagingSenderId: '29911992388',
    projectId: 'myfinance-8d2bf',
    storageBucket: 'myfinance-8d2bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdU4TUbhfV8tCTEc1pRxNlBFVKX0lXMU0',
    appId: '1:29911992388:ios:eb7ed6c1b23e0f5258d411',
    messagingSenderId: '29911992388',
    projectId: 'myfinance-8d2bf',
    storageBucket: 'myfinance-8d2bf.firebasestorage.app',
    androidClientId: '29911992388-7vc2gfsv95ealqq1ncb0tm5oevqa7fkq.apps.googleusercontent.com',
    iosClientId: '29911992388-fjslgcr6jc4ptb6pl0lt4ob9g192anuv.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdU4TUbhfV8tCTEc1pRxNlBFVKX0lXMU0',
    appId: '1:29911992388:ios:eb7ed6c1b23e0f5258d411',
    messagingSenderId: '29911992388',
    projectId: 'myfinance-8d2bf',
    storageBucket: 'myfinance-8d2bf.firebasestorage.app',
    androidClientId: '29911992388-7vc2gfsv95ealqq1ncb0tm5oevqa7fkq.apps.googleusercontent.com',
    iosClientId: '29911992388-fjslgcr6jc4ptb6pl0lt4ob9g192anuv.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTBcVF2OyDy_jk4eQDMUy-NKVQPfCJanQ',
    appId: '1:29911992388:web:c0d875425fa2744a58d411',
    messagingSenderId: '29911992388',
    projectId: 'myfinance-8d2bf',
    authDomain: 'myfinance-8d2bf.firebaseapp.com',
    storageBucket: 'myfinance-8d2bf.firebasestorage.app',
    measurementId: 'G-9K4EQ8CWEQ',
  );
}
